services:
  - type: web
    name: tb-detection-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
